### ISSUE TITLE
Discussion: Database hakkında geliştirme.

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/gelecekbilimde-backend#110]
Bugün yaptığım geliştirme esnasında database'ın bazı structurlarının oluşturulduğunu ancak bu structurlardan bazılarının sorunlu olduğunu farkettim. Örn. user_followers. Bu sorunlu tablolardan dolayı ve geliştirme esnasında yaşanabilecek problemlerden dolayı bir adet sql dosyası fresh bir proje db'si olarak proje'ye eklenebilir. Yeni başlayanlar setup'ı kolay yapabilir geliştirme yapanlarda hali hazırda oluşturulmuş db'de çıkan problemlerle vakit kaybetmez.

**Comment by agitrubard** [comment]
@alpemreelmas 
<img width="124" alt="image" src="https://github.com/user-attachments/assets/01871912-6e20-446e-b687-adbdd628db9a"> tartışmak istediğim konuları bu bölümde tartışabiliriz, issue'lar biraz daha yapılması gereken şeyler anlamına geliyor ✅
