### ISSUE TITLE
Backend Test Ortamı Kurulumu

### ISSUE THREAD

**Issue by Ciklamert** [gelecekbilimde/gelecekbilimde-backend#134]
- api.gelecekbilimde.net domaini yönlendirilecek @Ciklamert 
- Backend ortamı kurulacak
- Veritabanı kurulacak

Görevi alacak kişiye yetki @Ciklamert tarafından verilecektir. Benle iletişim kurabilir.

**Comment by agitrubard** [comment]
Linux Centos sunucusuna kurulumların yapıldıktan sonra uygulamanın veri tabanına bağlanamaması üzerine issue'yu blocked statüsüne aldım. Başka bir işletim sistemi kurulabilirse geliştirmeye devam edecem.
