### ISSUE TITLE
Gereksinimler ile alakalı docs'u Github Wiki'ye taşıma ve eksik yerlerin tamamlanması

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/gelecekbilimde-backend#146]
Front-end ve back-end için tüm gerekli bilgilerin bulunacağı bir dokümantasyon gerekli.

**Comment by Ciklamert** [comment]
@alpemreelmas @aleyna-yildizli eksik yerleri açıklamaya ekler misiniz? Ana olarak 1.fazda olması gerekenler şeklinde yazmıştık. Ona göre doldurayım, sonrasında Github wiki'ye taşıyayım.

**Comment by aleyna-yildizli** [comment]
Reddedilen başvuruların gösterilip gösterilmeyeceği konusunda bir bilgi yok. bir kullanıcı yazar veya moderatör olmak için başvuruda bulunduğunda ve bu başvuru reddedildiğinde, bu durumu kullanıcıya nasıl bildireceğiz? Ayrıca reddedilen başvurların neden reddedildiğine dair kullanıcıya geri bildirim sağlayacak mıyız? 

Yazar ve moderatör olmak için başvuruda bulunabilme ve bu başvuruların admin ve moderatör tarafından onaylanması haricinde ilk fazda başka bir bilgi bulunmuyor.

Başvuru durumunu ekranda göstermek (onaylandı, reddedildi, beklemede) ve reddedildi ise geri bildirim vermek ile ilgili ekleme yapabiliriz.

Toplantıdan hatırladığım kadarıyla @meminkecik bu konuda sorusu olmuştu. Eksik kısım varsa commentler misin? @meminkecik

**Comment by aleyna-yildizli** [comment]
Benim önerim faz-1'de
1. Kullanıcı, yazar/moderatör olma başvurusunu yaptıysa, başvuru durumunu görebilmeli (onaylandı, reddedildi, beklemede).
2. Onaylandıysa , "yazar/moderatör olma başvurunuz onaylandı..."
    Reddedildiyse, "yazar/moderatör olma başvurunuz reddedildi. Gerekçeyi öğrenmek için admin ile iletişime geçebilirsiniz."
yeterli olabilir.

faz-2 için
neden reddedildiğine dair kısa bir açıklama ve yeniden başvuru durumu için gerekçeler tartışılabilir.

**Comment by Ciklamert** [comment]
Kullanıcı Rol İsteği Gönderme Sayfası
-Kullanıcılar eğer kullanıcı rolüne sahip ise yazar olma rolüne ait, eğer yazar ise moderatör olma rolüne ait butonu ekranda görebilecektir.
-Butona basıldığında bir onay pop-up'ı çıkıp pop-up'da, "(Rol Adı) isteği göndermek istediğinize emin misiniz? Yazı yazma süreci hakkında daha fazla bilgi için https://gelecekbilimde.net/sitemizde-bir-yazi-nasil-yayimlaniyor/ yazısını ziyaret ediniz(Yazının başlığı yazılıp köprü eklenebilir.)
-Kişi isteği gönderdikten sonra profil sekmesinin altında gözükecek rol değişikliği isteklerim sekmesinden rol değişikliğinin durumunu görebilecektir. Aşağıdaki statüler olabilir.
-Değerlendirme(IN_ASSESSMENT)
-Red(Rejected)
-Onaylandı(Confirmed)
-Sayfanın alt kısmında "Eğer isteğiniz hakkında detaylı bilgi edinmek istiyorsanız yazi.isleri@gelecekbilimde.net adresi ile iletişime geçiniz." yazacaktır.

Kullanıcı Rol İstekleri Görüntüleme Sayfası-ADMİN
-Admin rol değişikliğinde bulunan kullanıcıları bir liste halinde görebilecektir.
-Listeleme ekranında kişinin adı-soyadı, emaili, hangi role yükselmek istediği yazacaktır.
-Listeleme ekranında hızlı düzenleme için Onayla ve Reddet butonları yer alacaktır.
-Bu ekranda kişinin üzerine tıklandığında kişinin profil detay sayfasına gidilecektir.


Gereksinim dosyası güncellenmiştir. Faz-2'de ticket ve bildirim mekanizması yürürlülüğe konacaktır. Onunla birlikte neden belirtme ve iletişime geçme halledilebilir. Faz-1 için yukarıdaki gereksinimler yeterlidir.

**Comment by aleyna-yildizli** [comment]
Teşekkürler @Ciklamert

**Comment by meminkecik** [comment]
-Admin rol değişikliğinde bulunan kullanıcıları bir liste halinde görebilecektir.
bu isterde bekleyen istekler mi görünsün sadece, yoksa kabul edilenler ve reddedilenler de görünsün mü?
Görünmeyecekse kabul edilen veya reddedilenlerin göründüğü ayrı bir sayfa mı olacak?

**Comment by alpemreelmas** [comment]
> -Admin rol değişikliğinde bulunan kullanıcıları bir liste halinde görebilecektir.
> bu isterde bekleyen istekler mi görünsün sadece, yoksa kabul edilenler ve reddedilenler de görünsün mü?
> Görünmeyecekse kabul edilen veya reddedilenlerin göründüğü ayrı bir sayfa mı olacak?

Benim tavsiyem, tüm isteklerin gözükmesi ve filterlanabilir şekilde olması. Bu sayede daha kullanışlı olacağını düşünüyorum

**Comment by Ciklamert** [comment]
Ilk aşamada  bekleyen ve reddilen istekler gözükebilir. Kabul edilenler user listesinde role göre filtreleme altında yazar olarak gözükeceği için gerek yoktur, reddedilenlere iletişim imkanı tanıdığımız için tutulabilir. Ancak burada admine isteği tamamen silme seçeneği sunulabilir. Gereksinim dosyasını buna göre güncellerim.

**Comment by aleyna-yildizli** [comment]
-Admin panelinde, kullanıcıların rol değişiklik talepleri üç ayrı duruma göre (bekleyen, kabul edilen, reddedilen) listelenebilir.
-Durum Filtreleme: Admin, talepleri durumlarına göre filtreleyebilir (örn. sadece bekleyen talepler, sadece kabul edilenler gibi).
 eklendi @meminkecik

**Comment by agitrubard** [comment]
@Ciklamert @aleyna-yildizli @alpemreelmas bu issue board üzerinde `DONE`a çekilmiş görünüyor fakat herhangi bir aksiyon alınmamış. Taşınma ve tamamlama kısmı bittiyse bu issue'yu kapatabilir miyiz?

**Comment by Ciklamert** [comment]
Admin kısmının düzenlenmesi bittikten sonra kapatılacaktır. @aleyna-yildizli Admin kısmını. bugün kategori modülü ile düzenledikten sonra kapatabilirsin.

**Comment by agitrubard** [comment]
@Ciklamert @aleyna-yildizli @alpemreelmas dokümantasyonu `https://github.com/gelecekbilimde/product` reposuna taşıdım. Buradaki wiki'de yazıları kaldırıyorum. Bundan sonraki doküman düzenlemelerini orada yapalım. Bu sayede herkesin ortak bakacağı yer orası olsun. Bütün ekipler için ortak bir nokta olur. Dokümanı da zaten bütün ekiplere uygun şekilde düzenliyoruz. Bu şekilde daha iyi olacağını düşünüyorum.
