### ISSUE TITLE
Github labelların daha kullanışlı hale getirilmesi

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/gelecekbilimde-backend#147]
https://github.com/afet-yonetim-sistemi/ays-be/labels örnek alınacaktır.

**Comment by Ciklamert** [comment]
Burada yapılacak işi açıklamaya girer misiniz ya da yapılması için bir toplantı düzenleyebilir miyiz? @aleyna-yildizli @alpemreelmas

**Comment by Ciklamert** [comment]
Labellar güncellenip gereksiz labellar silindi. Eklenmesi düşünülen bazı labellar eklendi. Şu anki issuelara bilgim dahilinde labellar ekledim. @aleyna-yildizli @alpemreelmas

**Comment by agitrubard** [comment]
@Ciklamert @aleyna-yildizli @alpemreelmas

- Versiyonlamayı labellardan yapmayalım. Milestone üzerinden yapalım. Bu sayede takip etmesi daha kolaylaşır.
- Label'larda birbiriyle örtüşmeyen kısımlar var gibi. Renklerine dikkat ederek tekrar düzenlenmeli.
  - Örneğin `In Development` diye bir label var fakat board üzerinde `In Progress` diye geçiyor. Kavram karmaşı yaratır.
  - Örneğin `Ready for Test` diye bir label var fakat board üzerinde böyle bir sütun yok. Bu tür durumlara dikkat etmek lazım.
  - Bazı label'ların açıklaması yok.
  - Priority Label'larının `Critical`, `Highest Priority`, `High Priority`, `Medium Priority`, `Low Priority`, `Lowest Priority` olarak detaylandırılması lazım. Bütün issue'lara bu önceliklerin tanımlanması lazım. kimin neyi yapabileceğini bilmesi lazım.
  - `Ready` gibi labellar gerekiyor. başlanabilecek issue'ları bu şekilde işaretlersek alabilecek kişiler bakarak hangisinin alınabilir olduğunu görür.

**Comment by alpemreelmas** [comment]
> @Ciklamert @aleyna-yildizli @alpemreelmas
> 
> - Versiyonlamayı labellardan yapmayalım. Milestone üzerinden yapalım. Bu sayede takip etmesi daha kolaylaşır.
> - Label'larda birbiriyle örtüşmeyen kısımlar var gibi. Renklerine dikkat ederek tekrar düzenlenmeli.
>   - Örneğin `In Development` diye bir label var fakat board üzerinde `In Progress` diye geçiyor. Kavram karmaşı yaratır.
>   - Örneğin `Ready for Test` diye bir label var fakat board üzerinde böyle bir sütun yok. Bu tür durumlara dikkat etmek lazım.
>   - Bazı label'ların açıklaması yok.
>   - Priority Label'larının `Critical`, `Highest Priority`, `High Priority`, `Medium Priority`, `Low Priority`, `Lowest Priority` olarak detaylandırılması lazım. Bütün issue'lara bu önceliklerin tanımlanması lazım. kimin neyi yapabileceğini bilmesi lazım.
>   - `Ready` gibi labellar gerekiyor. başlanabilecek issue'ları bu şekilde işaretlersek alabilecek kişiler bakarak hangisinin alınabilir olduğunu görür. 

Test yazmıyorsak ve testerlarımız yoksa kısaca kodu yazan kişi test ediyorsa yine de ready for test tarzı bir sütun koymalı mıyız ?

**Comment by Ciklamert** [comment]
Bence bu tip durumda ready for teste gerek yok. Test diye koyduğum label aslında geliştirmenin test ile alakalı olduğunu belirtmek için idi, ready for test bazında değildi. En geç yarına kadar tüm labelları düzenlerim yeniden açıklamaları ile, bir düzenleme olursa onun üzerinden düzenleyebilirsiniz. @alpemreelmas
