### ISSUE TITLE
Refresh Token api ucu düzenlemesi

### ISSUE THREAD

**Issue by halil-ulu** [gelecekbilimde/gelecekbilimde-backend#34]
`HttpServletRequest` alıp `Object` dönmek yerine diğer endpointlerde olduğu gibi özel bir request ve özel bir response oluşturup kullanmak en doğru yaklaşım olur

_Originally posted by @agitrubard in https://github.com/gelecekbilimde/gelecekbilimde-backend/pull/24#discussion_r1314281277_

**Comment by agitrubard** [comment]
https://github.com/gelecekbilimde/gelecekbilimde-backend/issues/126 numaralı issue ile aynı olduğundan kapatıldı.
